#!/usr/bin/env python3
"""Praxiswissen Seeding - Anleitungen, FAQs, Muster"""

import google.generativeai as genai
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct
import os
import uuid

genai.configure(api_key=os.environ['GEMINI_API_KEY'])
client = QdrantClient(host=os.environ['QDRANT_HOST'], port=6333, api_key=os.environ['QDRANT_API_KEY'], https=True)

def embed(text):
    return genai.embed_content(model='models/text-embedding-004', content=text[:8000])['embedding']

print('🚀 PRAXISWISSEN SEEDING')

praxis = [
    # Mietrecht Praxis
    {'title': 'Wie schreibe ich eine Mietminderungsanzeige?', 'content': 'Eine Mietminderungsanzeige muss folgende Elemente enthalten: 1. Genaue Beschreibung des Mangels mit Datum der Feststellung. 2. Aufforderung zur Beseitigung mit Fristsetzung (in der Regel 14 Tage). 3. Ankündigung der Mietminderung ab sofort. 4. Höhe der Minderung prozentual angeben. Die Anzeige sollte per Einschreiben mit Rückschein erfolgen. Fotos oder Protokolle als Beweis beifügen. Bei Schimmel ist eine Minderung von 20-50% üblich, bei Heizungsausfall im Winter bis zu 100%.', 'source': 'Praxisratgeber', 'category': 'Mietrecht', 'doc_type': 'Anleitung'},
    {'title': 'Nebenkostenabrechnung prüfen - Schritt für Schritt', 'content': 'Prüfung der Nebenkostenabrechnung: 1. Abrechnungszeitraum korrekt (max. 12 Monate)? 2. Frist eingehalten (12 Monate nach Abrechnungszeitraum)? 3. Verteilerschlüssel vereinbart und angewendet? 4. Nur umlagefähige Kosten nach BetrKV? 5. Plausibilität der Gesamtkosten prüfen. 6. Bei Zweifeln Belege anfordern (Frist: 12 Monate nach Zugang). Häufige Fehler: Instandhaltungskosten, Verwaltungskosten, Leerstandskosten zu Lasten der Mieter.', 'source': 'Praxisratgeber', 'category': 'Mietrecht', 'doc_type': 'Anleitung'},
    {'title': 'Widerspruch gegen Eigenbedarfskündigung', 'content': 'Widerspruch nach § 574 BGB: 1. Frist beachten: Spätestens 2 Monate vor Mietende. 2. Schriftform erforderlich. 3. Härtegründe darlegen: Alter, Krankheit, Schwangerschaft, lange Wohndauer, fehlender Ersatzwohnraum. 4. Nachweis der Härtegründe beifügen (Atteste, Bescheinigungen). 5. Interessenabwägung beantragen. Der Vermieter muss auf das Widerspruchsrecht im Kündigungsschreiben hinweisen.', 'source': 'Praxisratgeber', 'category': 'Mietrecht', 'doc_type': 'Anleitung'},
    {'title': 'Kaution richtig zurückfordern', 'content': 'Kautionsrückforderung nach Auszug: 1. Übergabeprotokoll anfertigen mit Zustand der Wohnung. 2. Abrechnungsfrist des Vermieters: 3-6 Monate. 3. Schriftliche Aufforderung mit Fristsetzung. 4. Zinsanspruch geltend machen (gesetzliche Anlage). 5. Berechtigung von Abzügen prüfen: Nur für tatsächliche Schäden, nicht für normale Abnutzung. 6. Bei Verweigerung: Mahnverfahren oder Klage beim Amtsgericht.', 'source': 'Praxisratgeber', 'category': 'Mietrecht', 'doc_type': 'Anleitung'},
    {'title': 'Mieterhöhung - Reaktionsmöglichkeiten', 'content': 'Bei Mieterhöhung nach § 558 BGB: 1. Formale Prüfung (schriftlich, Begründung, Mietspiegel?). 2. Vergleichsmiete prüfen (Mietspiegel, Vergleichswohnungen, Gutachten). 3. Kappungsgrenze beachten (20% in 3 Jahren, 15% in angespannten Märkten). 4. Zustimmungsfrist: 2 Monate. 5. Bei Ablehnung: Vermieter muss klagen. 6. Teilzustimmung möglich bei überhöhter Forderung. 7. Sonderkündigungsrecht bei Zustimmung.', 'source': 'Praxisratgeber', 'category': 'Mietrecht', 'doc_type': 'Anleitung'},
    
    # WEG Praxis
    {'title': 'Eigentümerversammlung vorbereiten und durchführen', 'content': 'Eigentümerversammlung: 1. Einladung durch Verwalter (3 Wochen vorher, Textform). 2. Tagesordnung mit allen Beschlusspunkten. 3. Vollmachten für abwesende Eigentümer. 4. Beschlussfähigkeit prüfen (mehr als 50% MEA anwesend). 5. Protokoll führen mit allen Beschlüssen. 6. Abstimmung nach Kopfprinzip oder MEA je nach Vereinbarung. 7. Unterschrift des Versammlungsleiters und eines Eigentümers. 8. Versand des Protokolls an alle Eigentümer.', 'source': 'Praxisratgeber', 'category': 'WEG', 'doc_type': 'Anleitung'},
    {'title': 'Beschlussanfechtung WEG richtig machen', 'content': 'Anfechtung eines WEG-Beschlusses: 1. Frist: 1 Monat ab Beschlussfassung (nicht ab Protokollerhalt). 2. Zuständig: Amtsgericht. 3. Anfechtungsgründe: Formfehler, Verstoß gegen Vereinbarung oder Gesetz, Ungleichbehandlung. 4. Parteien: Kläger gegen WEG-Gemeinschaft (nicht einzelne Eigentümer). 5. Kosten: Streitwert richtet sich nach Interesse. 6. Während des Verfahrens gilt der Beschluss weiterhin.', 'source': 'Praxisratgeber', 'category': 'WEG', 'doc_type': 'Anleitung'},
    {'title': 'Sonderumlage WEG - Rechte und Pflichten', 'content': 'Sonderumlage bei WEG: 1. Beschluss erforderlich mit einfacher Mehrheit. 2. Verwendungszweck muss angegeben sein. 3. Höhe muss verhältnismäßig sein. 4. Fälligkeit wird im Beschluss geregelt. 5. Ratenzahlung kann beschlossen werden. 6. Bei Eigentumswechsel: Beschlossene Sonderumlagen gehen auf Erwerber über. 7. Anfechtbar bei offensichtlicher Willkür oder falscher Berechnung.', 'source': 'Praxisratgeber', 'category': 'WEG', 'doc_type': 'Anleitung'},
    
    # Immobilienkauf Praxis
    {'title': 'Immobilienkauf Schritt für Schritt', 'content': 'Ablauf Immobilienkauf: 1. Besichtigung und Prüfung (Zustand, Lage, Grundbuch). 2. Finanzierungszusage einholen. 3. Reservierungsvereinbarung (optional). 4. Notartermin vereinbaren. 5. Kaufvertrag beim Notar beurkunden. 6. Auflassungsvormerkung im Grundbuch. 7. Kaufpreis nach Fälligkeitsmitteilung zahlen. 8. Grunderwerbsteuer zahlen (Unbedenklichkeitsbescheinigung). 9. Eigentumsumschreibung im Grundbuch. 10. Schlüsselübergabe und Besitzübergang.', 'source': 'Praxisratgeber', 'category': 'Grundstücksrecht', 'doc_type': 'Anleitung'},
    {'title': 'Was ist im Grundbuch zu prüfen vor Kauf?', 'content': 'Grundbuchprüfung vor Kauf: 1. Abteilung I: Eigentümer prüfen (Verkaufsberechtigung). 2. Abteilung II: Belastungen wie Wegerechte, Wohnrechte, Nießbrauch, Vormerkungen. 3. Abteilung III: Grundpfandrechte (Hypotheken, Grundschulden) - müssen gelöscht werden. 4. Altlasten im Baulastenverzeichnis prüfen. 5. Flurkarte und Bebauungsplan beim Bauamt einsehen. 6. Grundstücksgrenzen mit Katasteramt abgleichen.', 'source': 'Praxisratgeber', 'category': 'Grundstücksrecht', 'doc_type': 'Anleitung'},
    {'title': 'Grunderwerbsteuer Berechnung und Fälligkeit', 'content': 'Grunderwerbsteuer: 1. Bemessungsgrundlage: Kaufpreis ohne Inventar. 2. Steuersätze nach Bundesland: 3,5% (Bayern, Sachsen) bis 6,5% (Brandenburg, NRW, Schleswig-Holstein). 3. Fälligkeit: 1 Monat nach Steuerbescheid. 4. Keine GrESt bei Erbschaft, Schenkung oder Erwerb zwischen Ehegatten. 5. Unbedenklichkeitsbescheinigung erforderlich für Grundbucheintragung. 6. Käufer und Verkäufer haften gesamtschuldnerisch.', 'source': 'Praxisratgeber', 'category': 'Steuerrecht', 'doc_type': 'Anleitung'},
    
    # Baurecht Praxis
    {'title': 'Bauabnahme richtig durchführen', 'content': 'Bauabnahme Checkliste: 1. Begehung aller Räume mit Bauunternehmer. 2. Protokoll mit allen Mängeln erstellen. 3. Fotos von Mängeln anfertigen. 4. Frist für Mängelbeseitigung setzen. 5. Vorbehalt bekannter Mängel erklären. 6. Bei wesentlichen Mängeln: Abnahme verweigern. 7. Nach Abnahme beginnt Gewährleistungsfrist (5 Jahre). 8. Schlusszahlung erst nach Abnahme fällig. 9. Bei VOB-Vertrag: Fiktive Abnahme nach 12 Werktagen beachten.', 'source': 'Praxisratgeber', 'category': 'Baurecht', 'doc_type': 'Anleitung'},
    {'title': 'Baugenehmigung beantragen - Anleitung', 'content': 'Baugenehmigung beantragen: 1. Bauvoranfrage für grundsätzliche Genehmigungsfähigkeit (optional). 2. Bauantragsformulare beim Bauamt besorgen. 3. Erforderliche Unterlagen: Lageplan, Bauzeichnungen, Baubeschreibung, Berechnungen, Nachweis Standsicherheit. 4. Einreichung durch bauvorlageberechtigten Architekten/Ingenieur. 5. Nachbarbeteiligung (Unterschriften oder behördliche Benachrichtigung). 6. Bearbeitungszeit: 2-4 Monate. 7. Baugenehmigung 3 Jahre gültig.', 'source': 'Praxisratgeber', 'category': 'Baurecht', 'doc_type': 'Anleitung'},
    
    # Steuerrecht Praxis
    {'title': 'Vermietungsabsicht steuerlich nachweisen', 'content': 'Nachweis der Einkünfteerzielungsabsicht: 1. Inserieren auf Immobilienportalen dokumentieren. 2. Besichtigungstermine protokollieren. 3. Makler beauftragen und Nachweis aufbewahren. 4. Marktübliche Miete verlangen. 5. Renovierungsmaßnahmen für Vermietung durchführen. 6. Finanzierungskosten auch bei Leerstand absetzbar. 7. Bei dauerhaftem Leerstand: Prognose über 30 Jahre erstellen. 8. Ortsübliche Vermarktungsbemühungen nachweisen.', 'source': 'Praxisratgeber', 'category': 'Steuerrecht', 'doc_type': 'Anleitung'},
    {'title': 'Abschreibung Immobilie richtig berechnen', 'content': 'AfA bei vermieteten Immobilien: 1. Gebäudeanteil ermitteln (Kaufpreis minus Bodenwert). 2. AfA-Satz: 2% für Gebäude ab 1925, 2,5% vor 1925, 3% für Neubauten ab 2023. 3. Anschaffungsnebenkosten hinzurechnen (Notar, Grunderwerbsteuer, Makler). 4. Bei Denkmal: 9% in ersten 8 Jahren, 7% in folgenden 4 Jahren möglich. 5. Sonder-AfA § 7b für Mietwohnungsneubau: 5% zusätzlich in 4 Jahren. 6. AfA nicht bei Eigentumswohnung im Eigenheim.', 'source': 'Praxisratgeber', 'category': 'Steuerrecht', 'doc_type': 'Anleitung'},
    
    # Nachbarrecht Praxis
    {'title': 'Nachbarstreit wegen Lärm - Vorgehensweise', 'content': 'Bei Lärmbelästigung durch Nachbarn: 1. Lärmprotokoll führen (Datum, Uhrzeit, Art, Dauer). 2. Direkte Ansprache des Nachbarn versuchen. 3. Vermieter informieren (bei Mietwohnung). 4. Hausverwaltung einschalten (bei WEG). 5. Schriftliche Abmahnung an Störer. 6. Ordnungsamt bei Verstößen gegen Ruhezeiten. 7. Zivilklage auf Unterlassung bei Dauerstörung. 8. Mietminderung bei erheblicher Beeinträchtigung (10-50%). 9. Fristlose Kündigung bei nachhaltiger Pflichtverletzung.', 'source': 'Praxisratgeber', 'category': 'Nachbarrecht', 'doc_type': 'Anleitung'},
    {'title': 'Grenzbebauung - Was ist erlaubt?', 'content': 'Grenzbebauung und Abstandsflächen: 1. Mindestabstand je nach Landesbauordnung (meist 3m). 2. Abstandsfläche = Wandhöhe x Faktor (0,4-1,0 je nach Bundesland). 3. Privilegierte Bauteile: Garagen bis 9m Länge und 3m Höhe grenznah erlaubt. 4. Carports und Gartenhäuser oft genehmigungsfrei. 5. Einverständnis des Nachbarn ermöglicht Unterschreitung. 6. Baulast ins Baulastenverzeichnis eintragen. 7. Bestandsschutz für alte Gebäude. 8. Nachträgliche Genehmigung bei Überbau schwierig.', 'source': 'Praxisratgeber', 'category': 'Baurecht', 'doc_type': 'Anleitung'},
    
    # Maklerrecht Praxis
    {'title': 'Maklervertrag prüfen - Worauf achten?', 'content': 'Maklervertrag Checkliste: 1. Provisionshöhe (üblich: 3-6% plus MwSt beim Kauf, 2 Monatsmieten bei Vermietung). 2. Alleinauftrag oder einfacher Auftrag? 3. Laufzeit und Kündigungsmöglichkeit. 4. Nachweis- oder Vermittlungsprovision? 5. Erfolgsabhängigkeit (nur bei Abschluss). 6. Aufwendungsersatz bei Nichterfolg? 7. Bestellerprinzip bei Vermietung beachten. 8. Widerrufsrecht bei Fernabsatzverträgen (14 Tage).', 'source': 'Praxisratgeber', 'category': 'Maklerrecht', 'doc_type': 'Anleitung'},
    
    # FAQ-Sammlung
    {'title': 'FAQ: Wie viel Mieterhöhung ist zulässig?', 'content': 'Die zulässige Mieterhöhung richtet sich nach verschiedenen Faktoren: 1. Anpassung an ortsübliche Vergleichsmiete nach § 558 BGB mit Kappungsgrenze von 20% in 3 Jahren (15% in angespannten Märkten). 2. Staffelmiete oder Indexmiete nach Vereinbarung. 3. Modernisierungsmieterhöhung um 8% der Kosten. 4. Bei Neuvermietung: Mietpreisbremse in Gebieten mit angespanntem Wohnungsmarkt (max. 10% über Vergleichsmiete). 5. Die Miete muss mindestens 15 Monate unverändert sein.', 'source': 'FAQ', 'category': 'Mietrecht', 'doc_type': 'FAQ'},
    {'title': 'FAQ: Wann darf der Vermieter die Wohnung betreten?', 'content': 'Der Vermieter hat kein generelles Zutrittsrecht. Betreten ist nur erlaubt bei: 1. Notfällen (Wasserschaden, Feuer, Gas). 2. Vereinbarter Besichtigung mit angemessener Vorankündigung (24-48 Stunden). 3. Durchführung von Reparaturen nach Ankündigung. 4. Verkaufs- oder Neuvermietungsbesichtigungen in angemessenem Rahmen. 5. Ablesung von Messgeräten. Der Mieter kann den Zutritt verweigern, wenn kein berechtigter Grund vorliegt. Eigenmächtiges Betreten ist Hausfriedensbruch.', 'source': 'FAQ', 'category': 'Mietrecht', 'doc_type': 'FAQ'},
    {'title': 'FAQ: Was sind umlagefähige Nebenkosten?', 'content': 'Umlagefähige Nebenkosten nach § 2 BetrKV: 1. Grundsteuer. 2. Wasserversorgung und Entwässerung. 3. Heizkosten und Warmwasser. 4. Aufzugskosten. 5. Straßenreinigung und Müllabfuhr. 6. Gebäudereinigung und Ungezieferbekämpfung. 7. Gartenpflege. 8. Beleuchtung. 9. Schornsteinreinigung. 10. Sach- und Haftpflichtversicherung. 11. Hauswart. 12. Gemeinschaftsantenne/Kabel. Nicht umlagefähig: Verwaltungskosten, Instandhaltungsrücklagen, Reparaturen.', 'source': 'FAQ', 'category': 'Mietrecht', 'doc_type': 'FAQ'},
    {'title': 'FAQ: Was muss bei Auszug renoviert werden?', 'content': 'Renovierungspflicht bei Auszug: 1. Bei unrenovierter Übernahme: Keine Renovierungspflicht (BGH-Rechtsprechung). 2. Bei renovierter Übernahme: Nur bei wirksamer Renovierungsklausel. 3. Starre Fristen (alle X Jahre) sind unwirksam. 4. Normale Abnutzung muss nicht beseitigt werden. 5. Vereinbarter Endrenovierung muss Abnutzung berücksichtigen. 6. Keine Fachhandwerkerklausel zulässig. 7. Besenreine Übergabe ist Standard. 8. Dübellöcher verschließen bei mehr als ortsüblicher Anzahl.', 'source': 'FAQ', 'category': 'Mietrecht', 'doc_type': 'FAQ'},
    {'title': 'FAQ: Wer zahlt die Maklerprovision?', 'content': 'Maklerprovision: 1. Bei Vermietung: Bestellerprinzip - wer beauftragt, zahlt (meist Vermieter). Max. 2 Monatsmieten netto + MwSt. 2. Bei Wohnungskauf: Halbteilung seit Dezember 2020 - Käufer zahlt maximal so viel wie Verkäufer. Üblich 3-6% des Kaufpreises. 3. Bei Gewerbeimmobilien: Frei vereinbar. 4. Bei Ferienwohnungen: Bestellerprinzip gilt nicht. 5. Provision nur bei Erfolg geschuldet (Vertragsabschluss). 6. Voraussetzung: wirksamer Maklervertrag.', 'source': 'FAQ', 'category': 'Maklerrecht', 'doc_type': 'FAQ'},
    {'title': 'FAQ: Kann ich als Eigentümer jederzeit kündigen?', 'content': 'Kündigungsrecht des Eigentümer-Vermieters: 1. Ordentliche Kündigung nur bei berechtigtem Interesse (§ 573 BGB). 2. Berechtigte Gründe: Eigenbedarf, erhebliche Pflichtverletzung, wirtschaftliche Verwertung. 3. Kündigungsfristen: 3/6/9 Monate je nach Wohndauer. 4. Fristlose Kündigung bei Zahlungsverzug (2 Monatsmieten) oder nachhaltiger Pflichtverletzung. 5. Sperrfrist nach Umwandlung in Eigentumswohnung: 3-10 Jahre je nach Bundesland. 6. Kündigung muss begründet werden.', 'source': 'FAQ', 'category': 'Mietrecht', 'doc_type': 'FAQ'},
]

print(f'📤 Uploading {len(praxis)} Dokumente...')
points = []
for i, doc in enumerate(praxis):
    vector = embed(doc['content'])
    points.append(PointStruct(id=str(uuid.uuid4()), vector=vector, payload=doc))
    if (i+1) % 10 == 0:
        print(f'  📝 {i+1}/{len(praxis)} embedded...')

for i in range(0, len(points), 25):
    batch = points[i:i+25]
    client.upsert(collection_name='legal_documents', points=batch)
    print(f'  ✅ Batch {i//25+1}: {len(batch)} docs')

info = client.get_collection('legal_documents')
print(f'📊 Gesamt: {info.points_count} Dokumente')
